# config information
  level: error

database:
  enable: true #
  max_idle: 10 # max idle connections
  max_open: 100  #max open connections
  type: postgres # postgres
  name: ibax #
  ver:  20200902 #
  connect: host=127.0.0.1 port=5432 user=postgres dbname=scan sslmode=disable password=ibax20200916

# redis config information
redis:
  enable: true  #
  address: 127.0.0.1 # address
  port: 6379       # address
  password: ibax,&.0se # password

centrifugo:
  enable: true  #
  secret: "4597e75c-4376-42a6-8c1f-7e3fc7eb2114"  #
  url: "http://127.0.0.1:8000" # address
  socket: "wss://127.0.0.1:8000/connection/websocket" # address
  key: "5872a29c-25d3-45d8-b6f2-0b36c44407cd" #

crontab:
  fullnodeTime: "0 0/10 * * * ?"        #node map
  historyupdate: "0/10 * * * * ?"       #line chart
  statistics: "0/5 * * * * ?"          #statistics
  transaction: "0/10 * * * * ?"         #latest transaction
